apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-api
spec:
  selector:
    matchLabels:
      app: temperature-api
  template: 
    metadata:       
      labels:
        app: temperature-api
    spec:            
      containers:
      - name: temperature-api
        image: hhinke/temperature-api:latest
        ports:
        - containerPort: 8080         